package dev.komu.ahwen.jdbc

import java.io.File
import java.sql.*
import java.util.*
import java.util.concurrent.Executor

class AhwenConnection(dir: File) : Connection {

    private val db = AhwenDatabase(dir)

    override fun createStatement(): Statement =
        AhwenStatement(db)

    override fun getAutoCommit(): Boolean =
        true

    override fun setAutoCommit(autoCommit: Boolean) {
        error("currently only auto-commit is supported")
    }

    override fun prepareStatement(sql: String?): PreparedStatement {
        error("unsupported operation")
    }

    override fun prepareStatement(sql: String?, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement {
        error("unsupported operation")
    }

    override fun prepareStatement(sql: String?, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): PreparedStatement {
        error("unsupported operation")
    }

    override fun prepareStatement(sql: String?, autoGeneratedKeys: Int): PreparedStatement {
        error("unsupported operation")
    }

    override fun prepareStatement(sql: String?, columnIndexes: IntArray?): PreparedStatement {
        error("unsupported operation")
    }

    override fun prepareStatement(sql: String?, columnNames: Array<out String>?): PreparedStatement {
        error("unsupported operation")
    }

    override fun rollback() {
        error("unsupported operation")
    }

    override fun rollback(savepoint: Savepoint?) {
        error("unsupported operation")
    }

    override fun getHoldability(): Int {
        error("unsupported operation")
    }

    override fun setNetworkTimeout(executor: Executor?, milliseconds: Int) {
        error("unsupported operation")
    }

    override fun commit() {
        error("unsupported operation")
    }

    override fun <T : Any?> unwrap(iface: Class<T>?): T {
        error("unsupported operation")
    }

    override fun setTransactionIsolation(level: Int) {
        error("unsupported operation")
    }

    override fun abort(executor: Executor?) {
        error("unsupported operation")
    }

    override fun prepareCall(sql: String?): CallableStatement {
        error("unsupported operation")
    }

    override fun prepareCall(sql: String?, resultSetType: Int, resultSetConcurrency: Int): CallableStatement {
        error("unsupported operation")
    }

    override fun prepareCall(
        sql: String?,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int
    ): CallableStatement {
        error("unsupported operation")
    }

    override fun getClientInfo(name: String?): String {
        error("unsupported operation")
    }

    override fun getClientInfo(): Properties {
        error("unsupported operation")
    }

    override fun setCatalog(catalog: String?) {
        error("unsupported operation")
    }

    override fun getWarnings(): SQLWarning {
        error("unsupported operation")
    }

    override fun getCatalog(): String {
        error("unsupported operation")
    }

    override fun setHoldability(holdability: Int) {
        error("unsupported operation")
    }

    override fun getSchema(): String {
        error("unsupported operation")
    }

    override fun isValid(timeout: Int): Boolean {
        error("unsupported operation")
    }

    override fun close() {
        error("unsupported operation")
    }

    override fun isClosed(): Boolean {
        error("unsupported operation")
    }

    override fun createNClob(): NClob {
        error("unsupported operation")
    }

    override fun createBlob(): Blob {
        error("unsupported operation")
    }

    override fun createArrayOf(typeName: String?, elements: Array<out Any>?): java.sql.Array {
        error("unsupported operation")
    }

    override fun setReadOnly(readOnly: Boolean) {
        error("unsupported operation")
    }

    override fun isWrapperFor(iface: Class<*>?): Boolean {
        error("unsupported operation")
    }

    override fun nativeSQL(sql: String?): String {
        error("unsupported operation")
    }

    override fun createStruct(typeName: String?, attributes: Array<out Any>?): Struct {
        error("unsupported operation")
    }

    override fun setClientInfo(name: String?, value: String?) {
        error("unsupported operation")
    }

    override fun setClientInfo(properties: Properties?) {
        error("unsupported operation")
    }

    override fun releaseSavepoint(savepoint: Savepoint?) {
        error("unsupported operation")
    }

    override fun createClob(): Clob {
        error("unsupported operation")
    }

    override fun isReadOnly(): Boolean {
        error("unsupported operation")
    }

    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement {
        error("unsupported operation")
    }

    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): Statement {
        error("unsupported operation")
    }

    override fun setSavepoint(): Savepoint {
        error("unsupported operation")
    }

    override fun setSavepoint(name: String?): Savepoint {
        error("unsupported operation")
    }

    override fun getTypeMap(): MutableMap<String, Class<*>> {
        error("unsupported operation")
    }

    override fun clearWarnings() {
        error("unsupported operation")
    }

    override fun getMetaData(): DatabaseMetaData {
        error("unsupported operation")
    }

    override fun getTransactionIsolation(): Int {
        error("unsupported operation")
    }

    override fun setSchema(schema: String?) {
        error("unsupported operation")
    }

    override fun getNetworkTimeout(): Int {
        error("unsupported operation")
    }

    override fun setTypeMap(map: MutableMap<String, Class<*>>?) {
        error("unsupported operation")
    }

    override fun createSQLXML(): SQLXML {
        error("unsupported operation")
    }
}
